### ISSUE TITLE
Make daily challenge/take home instructions clearer

### ISSUE THREAD

**Issue by 22antonio** [GeekwiseAcademy/virtual-mobile-friendly-websites#10]
**Description**
Directions on daily challenges and take homes could be made to be more clear. We could number the instructions so students can more linearly follow directions. Looking at a wall of text can be overwhelming and numbering the directions could help to reduce that feeling of overwhelm.

Going further with the idea of separation we could try and separate instructions into content and GitHub instructions. Maybe have a standard so students know what to expect on each day. Reducing any challenges on the students could improve retention overall.

**Where is the Content Located?**
[Day 7 daily challenge] has a good example of intimidating instructions.

**Old Content**
This is what the day 7 daily challenge currently looks like:

> Create a new repository named "parallax-practice" (Use your bootstrap-boilerplate template)
> Add a collaborator
> Clone your own repository
> Create a new branch named daily-challenge
> Add any 2 fonts from [Google Fonts](https://fonts.google.com/) (Note: the example uses "Lobster" and "Open Sans")
> Add a navbar and a jumbotron with text
> Here's an example of what we're aiming for: [View Example](https://geekwiseacademy.github.io/virtual-mobile-friendly-websites/img/parallax-practice.jpg)
> Add, commit, and push your changes to your daily-challenge branch
> Open a PR and request review from your collaborator
> Review and approve eachother's PR
> Once approved, merge and delete your daily-challenge branch

**New Content**
We could change it to something like this instead:

> ### Daily Challenge Instructions
> 
> 1. Create a new repository named "parallax-practice" (Use your bootstrap-boilerplate template)
> 2. Clone your own repository
> 3. Create a new branch named daily-challenge
> 4. Add any 2 fonts from [Google Fonts](https://fonts.google.com/) (Note: the example uses "Lobster" and "Open Sans")
> 5. Add a navbar and a jumbotron with text
> 
> ### GitHub Instructions
> 
> 1. Add a collaborator
> 2. Add, commit, and push your changes to your daily-challenge branch
> 3. Open a PR and request review from your collaborator
> 4. Review and approve eachother's PR
> 5. Once approved, merge and delete your daily-challenge branch
> 
> **Example:** [View Example](https://geekwiseacademy.github.io/virtual-mobile-friendly-websites/img/parallax-practice.jpg)

**Note**: I'm suggesting these changes for all daily challenge and take home instructions not just day 7. I think a similar change for websites for beginners could also be beneficial. 

[Day 7 daily challenge]: https://geekwiseacademy.github.io/virtual-mobile-friendly-websites/seven.html

**Comment by ayojackay** [comment]
@22antonio, excellent suggestion! Erik pointed this out for Websites for Beginners, and I've had it on my list to update the same for MFW. So the next time you teach, you'll see improvement. I appreciate your time!
