### ISSUE TITLE
Jumbotron Retirement

### ISSUE THREAD

**Issue by 22antonio** [GeekwiseAcademy/virtual-mobile-friendly-websites#3]
**Description**
The newest version of bootstrap is version 5.0. Jumbotron is no longer available in this version. It's not completely gone, it's just required to be made using utilities so we need to update the material

**Where is the Content Located?**
five.html, Day 5, Bootstrap Jumbotron

**Old Content**
[Jumbotron Documentation](https://getbootstrap.com/docs/4.5/components/jumbotron/)

**New Content**
[The new way to do jumbotrons using utilities](https://getbootstrap.com/docs/5.0/examples/jumbotron/)

**Comment by ayojackay** [comment]
[Fixed and updated in commit](https://github.com/GeekwiseAcademy/virtual-mobile-friendly-websites/commit/3e40b34043976b6d4ba9fec52e7803b01696785f)

[Merge pull request ](https://github.com/GeekwiseAcademy/virtual-mobile-friendly-websites/commit/c57c03ad9bda1e06e1748b2beda832f80bbe6deb)

Closing #3
